kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4 # <-- this is the new apiVersion

nodes:
- role: control-plane # <-- master node
- role: worker # <-- worker node
- role: worker  # <-- worker node
- role: worker  # <-- worker node


# run => kind create cluster --config ./k8s/kind.yml --name=fullcycle